version: "3.9"
services:
  skybox.blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: skybox.blob-storage
    volumes:
      - azurite-data:/data
    ports:
      - "10000:10000"
    command : >
      azurite-blob
      --blobHost 0.0.0.0
      --blobPort 10000
      --location /data

volumes:
  azurite-data: